### ISSUE TITLE
Cleanup *.proto issues

### ISSUE THREAD

**Issue by meling** [quickfeed/quickfeed#653]
There are a few minor issues in ag.proto that should be cleaned up during the summer refactoring.

- [x] #685
- [x] Things related to database schema as discussed in #572 
- [x] Renaming fields as discussed in #641 
- [x] Replace string-based deadlines and time values with `timestamppb`, discussed in #432 and PR #486. (See issue on GORM and [this timestamp serializer](https://github.com/clouditor/clouditor/blob/v1.4.16/persistence/gorm/gorm.go#L219) for the database...)
- [x] #684
- [x] Remove `Providers` and `GetProviders()` no longer used by the frontend.
- [x] Check other older issues also
- [x] Check other TODO items in Go code
- [x] Rename `Path` to `Name` in `qf.Organization`
- [x] Rename `OrganizationPath` to `OrganizationName` in `qf.Course`
- [x] Remove `Assignment.runScriptContent` (is now in local filesystem)
- [x] Remove `Course.dockerfile` (is now in local filesystem)

**Comment by meling** [comment]
Closing this as all items listed are covered by other issues.
